pipelines:
  branches: 
      main: 
          - step:
                  name: release
                  script:
                      - curl -fsSL https://get.jetpack.io | bash -s -- --yes
                      - jetpack release -w $PROD_WORKSPACE