pipelines:
  branches: 
      main: 
          - step:
                  name: deploy
                  image: jetpackio/cli:0.1.0
                  script:
                      - jetpack release -w $PROD_WORKSPACE