pipelines:
  branches: 
      main: 
          - step:
                  name: Deploy
                  image: atlassian/default-image:2
                  script:
                      - curl -fsSL https://get.jetpack.io | bash -s -- --yes
                      - jetpack release -w 9eb6ddb9-7eda-4727-acbd-b98cc4d74ad0