pipelines:
  branches: 
      main: 
          - step:
                  name: deploy
                  script:
                      - curl -fsSL https://get.jetpack.io | bash -s -- --yes
                      - jetpack release -w $PROD_WORKSPACE -s api.dev.jetpack.io